Graphics update!
mspielberg/factorio-miniloader pull request #40
Opened 2020-04-09 07:11 UTC by kirazy

I made these masks for Krastorio... but I thought rather than try to make a mod to reskin Miniloaders it would be so much easier to just... update Miniloaders.

Specific changes:
- New graphics and masks for loader, inserter, item, and technology.
- Added color support for the Ultimate Belt reskin.
- Went through and calibrated the tints for all the supported mods.
- Added a function to obtain tints from hex color codes.

The core miniloaders:
![image](https://user-images.githubusercontent.com/35714562/78867651-441eb400-79f6-11ea-869c-a9568370fd84.png)

Ultimate belts, as an example, but all the supported mods have updated color matching:
![image](https://user-images.githubusercontent.com/35714562/78867678-500a7600-79f6-11ea-9c05-3f66bffd2632.png)

As an aside, I think you can probably drop support for Xander's mod and the old Krastorio mod. In Xander's case, there's no more expedited belt that I could find. And the old Krastorio mod is broken by a recent vanilla update (and is deprecated so will never work again).

2020-04-09 07:15 UTC, kirazy commented
Oh, forgot to include pictures of in-game icons/tech icons:
![image](https://user-images.githubusercontent.com/35714562/78868105-269e1a00-79f7-11ea-8d44-1b8445381de3.png)
![image](https://user-images.githubusercontent.com/35714562/78868134-33227280-79f7-11ea-95e2-1d7a6792654d.png)

2020-04-09 18:04 UTC, mspielberg requested changes
These look amazing! Thanks so much for putting in the work on all of this. I wasn't sure about the future status of Krastorio Legacy, but if it's no longer being updated it makes sense to drop support. I have a few minor stylistic comments. I can take care of them if you'd prefer, and I've love to get this merged and released to the world!

2020-04-09 18:04 UTC, mspielberg commented on prototypes/entities.lua
> +          {
To keep style consistent, could you change these to not vertically align the `=`, and put `{` on the same line as the `=`, like you do with front_patch and back_patch?

2020-04-09 18:04 UTC, mspielberg commented on prototypes/templates.lua
> +local function tint_from_hex(hex, alpha)
Could you use [util.color](https://github.com/wube/factorio-data/blob/master/core/lualib/util.lua#L65-L78)?

2020-04-09 18:04 UTC, mspielberg commented on data.lua
> +  create_miniloader("chute-", "", {"logistics"}, {r = 0.5, g = 0.5, b = 0.5, a = 0.82}, "underground-belt")
Could you use [util.color](https://github.com/wube/factorio-data/blob/master/core/lualib/util.lua#L65-L78) for consistency with below?

2020-04-09 18:10 UTC, kirazy commented
I'm happy to make the changes myself. Also thanks for bringing util.color to my attention, now I have to go make some changes after this in another of my mods...

2020-04-09 18:29 UTC, kirazy commented
Finished make the changes you asked for.

2020-04-10 07:01 UTC, merged

2020-04-20 20:03 UTC, bitwiseshiftleft commented
Thanks for all your work on this!

I do have a concern about the new graphics, though.  In my opinion the filtered and unfiltered miniloaders look too similar, so that it's hard to tell them apart at a glance either in inventory or once placed.  Also, vertically oriented miniloaders and underneathies are very similar, despite doing quite different things.

So maybe next time you change the graphics, could you consider making them more visually distinct?  Like maybe they could have some kind of controller on top, that would glow or otherwise be a different color on filtered miniloaders, instead of just a pink tint to the metal?